development:
  # adapter: async
  adapter: solid_cable
test:
  # adapter: test
  adapter: solid_cable
production:
  adapter: solid_cable
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: ecowave_production
